export const TablesAPI = {
    BOLSA : {
        TABLE_NAME : 'bolsa_rb',
        ID : 'id',
        NOME : 'nome',
        CODE : 'code',
        PRECO_DESCONTO : 'preco_desconto',
        PRECO_TOTAL : 'preco_total',
        PRECO_PARCELAS : 'preco_parcelas',
        PARCELAS : 'parcelas',
        POSICAO : 'posicao',
        LINK : 'link',
        ATIVO : 'ativo',
        DATA_ADICIONADO : 'data_adicionado',
    },
    FOTO_BOLSA : {
        TABLE_NAME : 'foto_bolsa_rb',
        ID : 'id',
        ID_BOLSA : 'id_bolsa',
        ID_IMAGEM : 'id_imagem',
    },
    IMAGEM : {
        TABLE_NAME : 'imagem_rb',
        ID : 'id',
        CAMINHO : 'caminho',
    },
    MIDIA : {
        TABLE_NAME : 'midia_rb',
        ID : 'id',
        CODE : 'code',
        LINK : 'link',
        POSICAO : 'posicao',
        ID_IMAGEM : 'id_imagem',
        ATIVO : 'ativo',
        DATA_ADICIONADO : 'data_adicionado',
    },
    PESSOA : {
        TABLE_NAME : 'pessoa_rb',
        ID : 'id',
        NOME : 'nome',
        SOBRENOME : 'sobrenome',
        EMAIL : 'email',
        SENHA : 'senha',
        ATIVO : 'ativo',
        DATA_ADICIONADO : 'data_adicionado',
    },
    TOKEN_ACCESS : {
        TABLE_NAME : 'token_access_rb',
        ID : 'id',
        PESSOA : 'id_pessoa',
        TOKEN : 'token',
        ATIVO : 'ativo',
        DATA_ADICIONADO : 'data_adicionado',
    },
};