export const SITE_NAME = 'Rafael Bernardes';
export const FANTASY_NAME = 'RAFAEL BERNARDES BOLSAS';
export const CNPJ = '17.119.749/0001-55';
export const PHONE = '(51) 98572-6070';
export const LOCAL = 'PORTO ALEGRE - RS - BRASIL';
export const DEVELOPER = 'Douglas Pereira Bernardes';
export const CONTACT_FACEBOOK = 'https://www.facebook.com/rafaelbernardesbolsas/';
export const CONTACT_INSTAGRAM = 'https://www.instagram.com/rbernardesbolsas/';
export const CONTACT_DEVELOPER = 'https://br.linkedin.com/in/developer-bernardes';
