export const TablesAPI = {
    BAG : {
        TABLE_NAME : 'bolsa_rb',
        ID : 'id',
        CODE : 'code',
        NAME : 'nome',
        DISCOUNT_PRICE : 'preco_desconto',
        TOTAL_PRICE : 'preco_total',
        INSTALLMENTS_PRICE : 'preco_parcelas',
        INSTALLMENTS : 'parcelas',
        POSITION : 'posicao',
        DEPOSIT : 'deposit',
        LINK : 'link',
        ACTIVE : 'ativo',
        CREATED_AT : 'data_adicionado',
    },
    BAG_IMAGE : {
        TABLE_NAME : 'foto_bolsa_rb',
        ID : 'id',
        BAG : 'id_bolsa',
        IMAGE : 'id_imagem',
        ACTIVE : 'ativo',
        CREATED_AT : 'data_adicionado',
    },
    IMAGE : {
        TABLE_NAME : 'imagem_rb',
        ID : 'id',
        LOCATION : 'caminho',
    },
    MEDIA : {
        TABLE_NAME : 'midia_rb',
        ID : 'id',
        CODE : 'code',
        LINK : 'link',
        POSITION : 'posicao',
        IMAGE : 'id_imagem',
        ACTIVE : 'ativo',
        CREATED_AT : 'data_adicionado',
    },
    SOCIAL_NETWORK : {
        TABLE_NAME : 'redes_sociais_rb',
        ID : 'id',
        CODE : 'code',
        LINK : 'link',
        POSITION : 'posicao',
        IMAGE : 'id_imagem',
        ACTIVE : 'ativo',
        CREATED_AT : 'data_adicionado',
    },
    USER : {
        TABLE_NAME : 'pessoa_rb',
        ID : 'id',
        NAME : 'nome',
        LASTNAME : 'sobrenome',
        EMAIL : 'email',
        PASSWORD : 'senha',
        SALT_PASSWORD : 'salt',
        ACTIVE : 'ativo',
        CREATED_AT : 'data_adicionado',
    },
    TOKEN_ACCESS : {
        TABLE_NAME : 'token_access_rb',
        ID : 'id',
        USER : 'id_pessoa',
        TOKEN : 'token',
        ACTIVE : 'ativo',
        CREATED_AT : 'data_adicionado',
    },
};